### ISSUE TITLE
图片无法解码

### ISSUE THREAD

**Issue by ybADMIN** [LuckyJayce/LargeImage#18]
```03-08 10:43:05.662 809-14006/com.huanmedia.yourchum.debug **W/System.err: java.io.IOException: Image failed to decode using JPEG decoder
03-08 10:43:05.672 809-1142/com.huanmedia.yourchum.debug D/ONE SDK: [2017/3/8 10:43:5:679]: [net] has wifi connection
03-08 10:43:05.672 809-14006/com.huanmedia.yourchum.debug W/System.err:     at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
03-08 10:43:05.672 809-14006/com.huanmedia.yourchum.debug W/System.err:     at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
03-08 10:43:05.682 809-14006/com.huanmedia.yourchum.debug W/System.err:     at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
03-08 10:43:05.682 809-14006/com.huanmedia.yourchum.debug W/System.err:     at com.shizhefei.view.largeimage.factory.FileBitmapDecoderFactory.made(FileBitmapDecoderFactory.java:23)
03-08 10:43:05.682 809-14006/com.huanmedia.yourchum.debug W/System.err:     at com.shizhefei.view.largeimage.BlockImageLoader$LoadHandler.handleMessage(BlockImageLoader.java:805)
03-08 10:43:05.692 809-14006/com.huanmedia.yourchum.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-08 10:43:05.692 809-14006/com.huanmedia.yourchum.debug W/System.err:     at android.os.Looper.loop(Looper.java:136)
03-08 10:43:05.692 809-14006/com.huanmedia.yourchum.debug W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by LuckyJayce** [comment]
你的图片多大

**Comment by ybADMIN** [comment]
这个问题已经解决了，原因是因为原图编码有些问题，重新编码就能解决，不过出现另一个问题
Bitmap too large to be uploaded into a texture (440x4431, max=4096x4096)

**Comment by ybADMIN** [comment]
[http://short.im.rockhippo.cn/uploads/msg/201703/20170309/1485/1489068660846.jpg](url)

**Comment by ybADMIN** [comment]
` if (cacheImageData == null) {
            //加载完整图片的缩略图
            try {
                int screenWidth = context.getResources().getDisplayMetrics().widthPixels;
                int screenHeight = context.getResources().getDisplayMetrics().heightPixels;
                int s = (int) Math.sqrt(1.0f * imageWidth * imageHeight / (screenWidth / 2) / (screenHeight / 2));
                cacheImageScale = getNearScale(s);
                if (cacheImageScale < s) {
                    cacheImageScale *= 2;
                }
                loadData.handler.sendMessage(loadData.handler.obtainMessage(MESSAGE_PIC, cacheImageScale));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }`

- 应该是这块代码中 getNearScale(s)计算有问题 图片计算后s值为1  getNearScale(s);得到的值也是1
因此会抛出
Bitmap too large to be uploaded into a texture (440x4431, max=4096x4096)
>

**Comment by ybADMIN** [comment]
` if (cacheImageData == null) {
            //加载完整图片的缩略图
            try {
                int screenWidth = context.getResources().getDisplayMetrics().widthPixels;
                int screenHeight = context.getResources().getDisplayMetrics().heightPixels;
                int s = (int) Math.sqrt(1.0f * imageWidth * imageHeight / (screenWidth / 2) / (screenHeight / 2));
                cacheImageScale = getNearScale(s);
                if (cacheImageScale < s) {
                    cacheImageScale *= 2;
                }
                loadData.handler.sendMessage(loadData.handler.obtainMessage(MESSAGE_PIC, cacheImageScale));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }`

**Comment by LuckyJayce** [comment]
那你解码后的图片是
http://short.im.rockhippo.cn/uploads/msg/201703/20170309/1485/1489068660846.jpg这个么？
还是解码前的
问题应该不在getNearScale(s)，因为s为1，说明图片要显示的不缩放的

**Comment by LuckyJayce** [comment]
调试了一下，Math.sqrt()之前是3.7 本来应该是2的，但是由于(int)导致3 Math.sqrt()后结果为1.的确和那个有关

**Comment by LuckyJayce** [comment]
调试了下本来缩放scale 1.9392987 结果(int)后变1，确定是你说的那个原因

**Comment by ybADMIN** [comment]
scale 1.9392987 结果(int)后变1
如果是不缩放的话就会
Bitmap too large to be uploaded into a texture (440x4431, max=4096x4096)
你没有遇到这个问题？

**Comment by LuckyJayce** [comment]
已处理
